import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

enum HabitType { develop, quit, task }

enum HabitRepeat { daily, custom }

enum HabitTiming { anytime, morning, noon, afternoon, evening, night }

class HabitsItems {
  static const weekdays = ["S", "M", "T", "W", "T", "F", "S"];

  static const List<Map<String, dynamic>> habitCategories = [
    {"id": "0", "name": "All", "icon": Icons.list},
    {"id": "1", "name": "Develop", "icon": Icons.flag_outlined},
    {"id": "2", "name": "Quit", "icon": Icons.block},
    {"id": "3", "name": "Task", "icon": Icons.check_circle_outline},
    {"id": "4", "name": "Health", "icon": Icons.fitness_center},
    {"id": "5", "name": "Productivity", "icon": Icons.work_outline},
    {"id": "6", "name": "Mindfulness", "icon": Icons.self_improvement},
    {"id": "7", "name": "Lifestyle", "icon": Icons.home_outlined},
    {"id": "8", "name": "Social", "icon": Icons.groups_outlined},
    {"id": "9", "name": "Motivation", "icon": Icons.star_outline},
  ];

  static const List<Map<String, dynamic>> habitList = [
    // Habits to Develop (categoryId: "1")
    {
      "id": "1",
      "name": "Workout",
      "icon": Icons.fitness_center_outlined,
      "categoryId": "1",
      "countOptions": ["once", "minute", "hour", "session"],
    },
    {
      "id": "2",
      "name": "Drink Water",
      "icon": Icons.local_drink_outlined,
      "categoryId": "1",
      "countOptions": ["glass", "bottle", "liter", "times"],
    },
    {
      "id": "3",
      "name": "Eat Fruits",
      "icon": Icons.apple,
      "categoryId": "1",
      "countOptions": ["piece", "cup", "serving", "times"],
    },
    {
      "id": "4",
      "name": "Meditate",
      "icon": Icons.self_improvement,
      "categoryId": "1",
      "countOptions": ["minute", "session", "hour"],
    },
    {
      "id": "5",
      "name": "Read",
      "icon": Icons.book_outlined,
      "categoryId": "1",
      "countOptions": ["minute", "hour", "page", "chapter", "session"],
    },
    {
      "id": "6",
      "name": "Journal",
      "icon": Icons.edit,
      "categoryId": "1",
      "countOptions": ["entry", "minute", "words", "session"],
    },
    {
      "id": "7",
      "name": "Sleep Early",
      "icon": Icons.nightlight_round,
      "categoryId": "1",
      "countOptions": ["before", "hours", "sleepBy", "times"],
    },
    {
      "id": "8",
      "name": "Organize Daily Tasks",
      "icon": Icons.format_list_bulleted,
      "categoryId": "1",
      "countOptions": ["task", "tasks", "minute", "session"],
    },
    {
      "id": "9",
      "name": "Practice Gratitude",
      "icon": Icons.favorite_outline,
      "categoryId": "1",
      "countOptions": ["item", "items", "minute", "session"],
    },
    {
      "id": "10",
      "name": "Connect with Others",
      "icon": Icons.people_outline,
      "categoryId": "1",
      "countOptions": ["call", "message", "meet", "minute"],
    },

    // Habits to Quit (categoryId: "2")
    {
      "id": "11",
      "name": "Binge Watching",
      "icon": Icons.tv_off,
      "categoryId": "2",
      "countOptions": ["none", "minute", "hour", "episode", "times"],
    },
    {
      "id": "12",
      "name": "Skipping Meals",
      "icon": Icons.no_food,
      "categoryId": "2",
      "countOptions": ["none", "skip", "meals", "times"],
    },
    {
      "id": "13",
      "name": "Smoking",
      "icon": Icons.smoke_free,
      "categoryId": "2",
      "countOptions": ["none", "times", "delay", "session"],
    },
    {
      "id": "14",
      "name": "Negative Self-Talk",
      "icon": Icons.do_not_disturb_on,
      "categoryId": "2",
      "countOptions": ["none", "statement", "replace", "affirmation"],
    },
    {
      "id": "15",
      "name": "Procrastination",
      "icon": Icons.snooze,
      "categoryId": "2",
      "countOptions": ["start", "minute", "session", "times"],
    },
    {
      "id": "16",
      "name": "Excessive Screen Time",
      "icon": Icons.phonelink_off,
      "categoryId": "2",
      "countOptions": ["none", "minute", "hour", "cutoff"],
    },
    {
      "id": "17",
      "name": "Poor Sleep Habits",
      "icon": Icons.bedtime_off,
      "categoryId": "2",
      "countOptions": ["sleepBy", "none", "hours", "nap"],
    },
    {
      "id": "18",
      "name": "Impulse Shopping",
      "icon": Icons.remove_shopping_cart,
      "categoryId": "2",
      "countOptions": ["none", "times", "waitRule", "session"],
    },
    {
      "id": "19",
      "name": "Nail Biting",
      "icon": Icons.pan_tool_outlined,
      "categoryId": "2",
      "countOptions": ["none", "episode", "times", "substitute"],
    },
    {
      "id": "20",
      "name": "Saying Yes to Everything",
      "icon": Icons.no_accounts,
      "categoryId": "2",
      "countOptions": ["pause", "no", "times", "session"],
    },

    // One-Time Tasks (categoryId: "3")
    {
      "id": "21",
      "name": "Declutter Workspace",
      "icon": Icons.cleaning_services_outlined,
      "categoryId": "3",
      "countOptions": ["once", "minute", "hour", "session"],
    },
    {
      "id": "22",
      "name": "Schedule Medical Checkup",
      "icon": Icons.medical_services_outlined,
      "categoryId": "3",
      "countOptions": ["once", "book", "appointment"],
    },
    {
      "id": "23",
      "name": "Plan Monthly Budget",
      "icon": Icons.account_balance_wallet_outlined,
      "categoryId": "3",
      "countOptions": ["once", "minute", "hour", "session"],
    },
    {
      "id": "24",
      "name": "Organize Bookshelf",
      "icon": Icons.shelves,
      "categoryId": "3",
      "countOptions": ["once", "minute", "hour"],
    },
    {
      "id": "25",
      "name": "Batch Cook Meals",
      "icon": Icons.kitchen,
      "categoryId": "3",
      "countOptions": ["once", "hour", "session"],
    },
    {
      "id": "26",
      "name": "Sort Mail",
      "icon": Icons.mail_outline,
      "categoryId": "3",
      "countOptions": ["once", "minute", "session"],
    },
    {
      "id": "27",
      "name": "Prep Next-Day Clothes",
      "icon": Icons.checkroom,
      "categoryId": "3",
      "countOptions": ["once", "outfit", "daily"],
    },
    {
      "id": "28",
      "name": "Clean Drop Zone",
      "icon": Icons.home_outlined,
      "categoryId": "3",
      "countOptions": ["once", "minute", "session"],
    },
    {
      "id": "29",
      "name": "Backup Digital Files",
      "icon": Icons.backup,
      "categoryId": "3",
      "countOptions": ["once", "weekly", "monthly"],
    },
    {
      "id": "31",
      "name": "Update Personal Records",
      "icon": Icons.folder_open,
      "categoryId": "3",
      "countOptions": ["once", "minute", "session"],
    },

    // Extended Habits from iconList with category mapping
    // Health & Wellness (categoryId: "4")
    {
      "id": "32",
      "name": "Running",
      "icon": Icons.directions_run_outlined,
      "categoryId": "4",
      "countOptions": ["km", "minute", "hour", "session"],
    },
    {
      "id": "33",
      "name": "Sports",
      "icon": Icons.sports_basketball_outlined,
      "categoryId": "4",
      "countOptions": ["minute", "hour", "session", "times"],
    },
    {
      "id": "34",
      "name": "Cycling",
      "icon": Icons.pedal_bike_outlined,
      "categoryId": "4",
      "countOptions": ["km", "minute", "hour", "session"],
    },
    {
      "id": "35",
      "name": "Swimming",
      "icon": Icons.pool_outlined,
      "categoryId": "4",
      "countOptions": ["minute", "laps", "session", "hour"],
    },
    {
      "id": "36",
      "name": "Meditation",
      "icon": Icons.self_improvement_outlined,
      "categoryId": "6",
      "countOptions": ["minute", "session", "hour"],
    },
    {
      "id": "37",
      "name": "Eating Healthy",
      "icon": Icons.local_dining_outlined,
      "categoryId": "4",
      "countOptions": ["meal", "meals", "swap", "serving"],
    },
    {
      "id": "38",
      "name": "Meal Prep",
      "icon": Icons.set_meal_outlined,
      "categoryId": "7",
      "countOptions": ["batch", "minute", "hour", "session"],
    },
    {
      "id": "39",
      "name": "Hydration",
      "icon": Icons.water_drop_outlined,
      "categoryId": "4",
      "countOptions": ["glass", "bottle", "liter", "times"],
    },
    {
      "id": "40",
      "name": "Nature Walk",
      "icon": Icons.eco_outlined,
      "categoryId": "4",
      "countOptions": ["minute", "walk", "session"],
    },
    {
      "id": "41",
      "name": "Heart Health",
      "icon": CupertinoIcons.heart,
      "categoryId": "4",
      "countOptions": ["cardio", "minute", "session", "times"],
    },
    {
      "id": "42",
      "name": "Morning Routine",
      "icon": CupertinoIcons.sun_max,
      "categoryId": "7",
      "countOptions": ["minute", "routine", "session", "daily"],
    },
    {
      "id": "43",
      "name": "Night Routine",
      "icon": CupertinoIcons.moon,
      "categoryId": "7",
      "countOptions": ["minute", "routine", "session", "daily"],
    },
    {
      "id": "44",
      "name": "Sleep",
      "icon": Icons.bedtime_outlined,
      "categoryId": "4",
      "countOptions": ["hours", "sleepBy", "times", "session"],
    },
    {
      "id": "45",
      "name": "Relaxation",
      "icon": Icons.spa_outlined,
      "categoryId": "6",
      "countOptions": ["minute", "session", "hour"],
    },
    {
      "id": "46",
      "name": "Recovery",
      "icon": Icons.healing_outlined,
      "categoryId": "4",
      "countOptions": ["minute", "session", "times"],
    },
    {
      "id": "47",
      "name": "Heart Rate",
      "icon": Icons.monitor_heart_outlined,
      "categoryId": "4",
      "countOptions": ["measure", "times", "session"],
    },
    {
      "id": "48",
      "name": "Hiking",
      "icon": Icons.hiking,
      "categoryId": "4",
      "countOptions": ["km", "walk", "session", "times"],
    },
    {
      "id": "49",
      "name": "Balance",
      "icon": Icons.balance_outlined,
      "categoryId": "4",
      "countOptions": ["minute", "session", "times"],
    },

    // Productivity & Learning (categoryId: "5")
    {
      "id": "50",
      "name": "Reading",
      "icon": Icons.menu_book_outlined,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "page", "chapter", "session"],
    },
    {
      "id": "51",
      "name": "Daily Reading",
      "icon": Icons.auto_stories_outlined,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "session"],
    },
    {
      "id": "52",
      "name": "Journaling",
      "icon": Icons.edit_outlined,
      "categoryId": "5",
      "countOptions": ["entry", "minute", "words", "session"],
    },
    {
      "id": "53",
      "name": "Studying",
      "icon": Icons.school_outlined,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "session", "blocks"],
    },
    {
      "id": "54",
      "name": "New Idea",
      "icon": Icons.lightbulb_outline,
      "categoryId": "5",
      "countOptions": ["note", "idea", "minute", "session"],
    },
    {
      "id": "55",
      "name": "Wake Early",
      "icon": Icons.alarm_outlined,
      "categoryId": "5",
      "countOptions": ["by", "time", "daily"],
    },
    {
      "id": "56",
      "name": "Time Discipline",
      "icon": Icons.alarm_on_outlined,
      "categoryId": "5",
      "countOptions": ["start", "blocks", "minute", "session"],
    },
    {
      "id": "57",
      "name": "Work Study",
      "icon": Icons.laptop_mac_outlined,
      "categoryId": "5",
      "countOptions": ["hour", "session", "blocks"],
    },
    {
      "id": "58",
      "name": "Coding",
      "icon": Icons.keyboard_outlined,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "session", "problem"],
    },
    {
      "id": "59",
      "name": "Learning",
      "icon": CupertinoIcons.book,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "lesson", "session"],
    },
    {
      "id": "60",
      "name": "Time Management",
      "icon": CupertinoIcons.time,
      "categoryId": "5",
      "countOptions": ["minute", "plan", "review", "session"],
    },
    {
      "id": "61",
      "name": "Writing",
      "icon": CupertinoIcons.doc_text,
      "categoryId": "5",
      "countOptions": ["minute", "hour", "words", "session"],
    },
    {
      "id": "62",
      "name": "Daily Updates",
      "icon": CupertinoIcons.news,
      "categoryId": "5",
      "countOptions": ["update", "minute", "session"],
    },
    {
      "id": "63",
      "name": "Planning",
      "icon": Icons.task_outlined,
      "categoryId": "5",
      "countOptions": ["task", "tasks", "minute", "session"],
    },
    {
      "id": "64",
      "name": "Tracking",
      "icon": Icons.list_alt_outlined,
      "categoryId": "5",
      "countOptions": ["once", "daily", "weekly", "minute"],
    },

    // Mindfulness & Self Growth (categoryId: "6")
    {
      "id": "65",
      "name": "Task Completion",
      "icon": Icons.check_circle_outline,
      "categoryId": "6",
      "countOptions": ["task", "tasks", "times", "session"],
    },
    {
      "id": "66",
      "name": "Mindfulness",
      "icon": Icons.psychology_outlined,
      "categoryId": "6",
      "countOptions": ["minute", "session", "hour"],
    },
    {
      "id": "67",
      "name": "Gratitude",
      "icon": Icons.volunteer_activism_outlined,
      "categoryId": "6",
      "countOptions": ["item", "items", "minute", "session"],
    },
    {
      "id": "68",
      "name": "Positivity",
      "icon": Icons.wb_sunny_outlined,
      "categoryId": "6",
      "countOptions": ["affirmation", "minute", "session"],
    },
    {
      "id": "69",
      "name": "Progress",
      "icon": Icons.auto_graph_outlined,
      "categoryId": "6",
      "countOptions": ["log", "daily", "weekly", "session"],
    },
    {
      "id": "70",
      "name": "Reflection",
      "icon": Icons.insights_outlined,
      "categoryId": "6",
      "countOptions": ["minute", "session", "entry"],
    },
    {
      "id": "71",
      "name": "Kindness",
      "icon": Icons.handshake_outlined,
      "categoryId": "6",
      "countOptions": ["act", "acts", "times", "session"],
    },
    {
      "id": "72",
      "name": "Self Love",
      "icon": Icons.favorite_border,
      "categoryId": "6",
      "countOptions": ["act", "minute", "session"],
    },
    {
      "id": "73",
      "name": "Confidence",
      "icon": Icons.shield_outlined,
      "categoryId": "6",
      "countOptions": ["affirmation", "win", "session"],
    },
    {
      "id": "74",
      "name": "Curiosity",
      "icon": Icons.catching_pokemon,
      "categoryId": "6",
      "countOptions": ["question", "minute", "session"],
    },
    {
      "id": "75",
      "name": "Calmness",
      "icon": Icons.nightlight_outlined,
      "categoryId": "6",
      "countOptions": ["minute", "session", "breath"],
    },

    // Lifestyle & Routine (categoryId: "7")
    {
      "id": "76",
      "name": "Cleaning",
      "icon": Icons.cleaning_services_outlined,
      "categoryId": "7",
      "countOptions": ["minute", "hour", "task", "session"],
    },
    {
      "id": "77",
      "name": "Gardening",
      "icon": Icons.local_florist_outlined,
      "categoryId": "7",
      "countOptions": ["minute", "session", "times", "plant"],
    },
    {
      "id": "78",
      "name": "Grocery",
      "icon": Icons.shopping_cart_outlined,
      "categoryId": "7",
      "countOptions": ["weekly", "biweekly", "monthly", "trip"],
    },
    {
      "id": "79",
      "name": "Budgeting",
      "icon": Icons.attach_money_outlined,
      "categoryId": "7",
      "countOptions": ["monthly", "weekly", "minute", "session"],
    },
    {
      "id": "80",
      "name": "Pet Care",
      "icon": Icons.pets_outlined,
      "categoryId": "7",
      "countOptions": ["feed", "walk", "groom", "times"],
    },
    {
      "id": "81",
      "name": "Music",
      "icon": Icons.music_note_outlined,
      "categoryId": "7",
      "countOptions": ["minute", "hour", "session"],
    },
    {
      "id": "82",
      "name": "Art",
      "icon": Icons.brush_outlined,
      "categoryId": "7",
      "countOptions": ["minute", "hour", "session"],
    },
    {
      "id": "83",
      "name": "DIY",
      "icon": Icons.construction_outlined,
      "categoryId": "7",
      "countOptions": ["project", "minute", "hour", "session"],
    },
    {
      "id": "84",
      "name": "Schedule",
      "icon": CupertinoIcons.calendar,
      "categoryId": "7",
      "countOptions": ["daily", "weekly", "minute"],
    },
    {
      "id": "85",
      "name": "Work",
      "icon": CupertinoIcons.briefcase,
      "categoryId": "7",
      "countOptions": ["hour", "session", "focus"],
    },
    {
      "id": "86",
      "name": "Grooming",
      "icon": CupertinoIcons.scissors,
      "categoryId": "7",
      "countOptions": ["daily", "weekly", "times"],
    },
    {
      "id": "87",
      "name": "Home Care",
      "icon": CupertinoIcons.house,
      "categoryId": "7",
      "countOptions": ["daily", "weekly", "monthly", "task"],
    },
    {
      "id": "88",
      "name": "Self Care",
      "icon": CupertinoIcons.wand_stars,
      "categoryId": "7",
      "countOptions": ["minute", "hour", "session", "weekly"],
    },
    {
      "id": "89",
      "name": "Cooking",
      "icon": Icons.kitchen_outlined,
      "categoryId": "7",
      "countOptions": ["meal", "times", "minute", "session"],
    },
    {
      "id": "90",
      "name": "Organization",
      "icon": Icons.folder_open_outlined,
      "categoryId": "7",
      "countOptions": ["task", "minute", "session"],
    },

    // Social & Digital Habits (categoryId: "8")
    {
      "id": "91",
      "name": "Call",
      "icon": Icons.phone_outlined,
      "categoryId": "8",
      "countOptions": ["call", "minute", "session", "times"],
    },
    {
      "id": "92",
      "name": "Email",
      "icon": Icons.mail_outline,
      "categoryId": "8",
      "countOptions": ["check", "respond", "daily", "weekly"],
    },
    {
      "id": "93",
      "name": "Message",
      "icon": Icons.sms_outlined,
      "categoryId": "8",
      "countOptions": ["reply", "message", "minute", "times"],
    },
    {
      "id": "94",
      "name": "Social",
      "icon": Icons.groups_outlined,
      "categoryId": "8",
      "countOptions": ["engage", "minute", "hour", "limit"],
    },
    {
      "id": "95",
      "name": "Culture",
      "icon": Icons.public_outlined,
      "categoryId": "8",
      "countOptions": ["article", "watch", "weekly", "monthly"],
    },
    {
      "id": "96",
      "name": "Digital Detox",
      "icon": Icons.lock_clock,
      "categoryId": "8",
      "countOptions": ["none", "hour", "daily", "detoxDay"],
    },
    {
      "id": "97",
      "name": "Privacy",
      "icon": Icons.no_photography_outlined,
      "categoryId": "8",
      "countOptions": ["review", "disable", "monthly"],
    },
    {
      "id": "98",
      "name": "App Usage",
      "icon": CupertinoIcons.device_phone_portrait,
      "categoryId": "8",
      "countOptions": ["limit", "minute", "hour", "productiveOnly"],
    },
    {
      "id": "99",
      "name": "Communication",
      "icon": CupertinoIcons.chat_bubble,
      "categoryId": "8",
      "countOptions": ["convo", "message", "times"],
    },
    {
      "id": "100",
      "name": "Networking",
      "icon": Icons.wifi_tethering_outlined,
      "categoryId": "8",
      "countOptions": ["message", "attend", "monthly", "times"],
    },
    {
      "id": "101",
      "name": "Video Call",
      "icon": Icons.videocam_outlined,
      "categoryId": "8",
      "countOptions": ["minute", "session", "call"],
    },

    // Motivation / Meta (categoryId: "9")
    {
      "id": "102",
      "name": "Reward",
      "icon": Icons.star_outline,
      "categoryId": "9",
      "countOptions": ["reward", "weekly", "monthly", "afterStreak"],
    },
    {
      "id": "103",
      "name": "Goal",
      "icon": Icons.flag_outlined,
      "categoryId": "9",
      "countOptions": ["short", "medium", "long", "step"],
    },
    {
      "id": "104",
      "name": "Long Term Goal",
      "icon": Icons.track_changes_outlined,
      "categoryId": "9",
      "countOptions": ["milestone", "review", "monthly"],
    },
    {
      "id": "105",
      "name": "New Habit",
      "icon": Icons.rocket_launch_outlined,
      "categoryId": "9",
      "countOptions": ["try", "days", "challenge"],
    },
    {
      "id": "106",
      "name": "Improve",
      "icon": Icons.upgrade_outlined,
      "categoryId": "9",
      "countOptions": ["percent", "task", "weekly"],
    },
    {
      "id": "107",
      "name": "Milestone",
      "icon": Icons.emoji_events_outlined,
      "categoryId": "9",
      "countOptions": ["celebrate", "after", "times"],
    },
    {
      "id": "108",
      "name": "Consistency",
      "icon": Icons.repeat_on_outlined,
      "categoryId": "9",
      "countOptions": ["daily", "weekly", "times"],
    },
  ];
  static const List<String> goalUnits = [
    // General Count

    "count",
    "task",
    "session",
    "repetition",

    // Steps & Distance
    "step",
    "meter",
    "kilometer",
    "mile",

    // Time
    "second",
    "minute",
    "hour",

    // Volume (Water / Drinks)
    "milliliter",
    "liter",
    "glass",
    "cup",
    "bottle",
    "ounce",
    "gram",
    "kilogram",
    "milligram",
    "calorie",
    "page",
    "paragraph",
    "chapter",
    "point",
    "round",
    "set",
    "pound",
    "rep",
    "set",
    "word",
    "line",
    "email",
  ];
}
